#!/usr/bin/env python3
"""Generate independent INT8 regression fixtures with the desktop LiteRT interpreter.

Run from the repository root after installing tools/model_requirements.txt in a
virtual environment. This intentionally requires explicit regeneration when the
model or scaler changes; the native tests consume the checked-in result.
"""

import hashlib
import importlib.metadata
from pathlib import Path
import re

import numpy as np
from ai_edge_litert.interpreter import Interpreter, OpResolverType


ROOT = Path(__file__).resolve().parents[1]


def main():
    model_source = (ROOT / "main/model/model_data.cc").read_text()
    model = bytes(int(value, 16) for value in re.findall(r"0x([0-9a-fA-F]{2})", model_source))
    scaler = (ROOT / "main/model/scaler_data.h").read_text()

    def array(name):
        match = re.search(rf"{name}\[[^]]+\]\s*=\s*\{{([^}}]+)\}}", scaler)
        if not match:
            raise ValueError(f"Missing {name}")
        return np.array([float(v.strip().removesuffix("f"))
                         for v in match[1].split(",")], dtype=np.float32)

    mean, scale = array("kScalerMean"), array("kScalerScale")
    interpreter = Interpreter(model_content=model, num_threads=1,
                              experimental_op_resolver_type=OpResolverType.BUILTIN_REF)
    interpreter.allocate_tensors()
    input_info, = interpreter.get_input_details()
    output_info, = interpreter.get_output_details()
    assert input_info["dtype"] == np.int8 and list(input_info["shape"]) == [1, 600]
    assert output_info["dtype"] == np.int8 and list(output_info["shape"]) == [1, 1]
    input_scale, input_zero = input_info["quantization"]
    output_scale, output_zero = output_info["quantization"]

    stationary = np.tile(np.array([0, -1, 0], dtype=np.float32), (200, 1))
    periodic = stationary.copy()
    for i in range(200):
        periodic[i] += np.array([(i % 32 - 16) / 32,
                                 (i % 16 - 8) / 32,
                                 (i % 24 - 12) / 32], dtype=np.float32)
    impact = stationary.copy()
    impact[80:90] = [0, 0, 0]
    impact[90:95] = [4, -6, 2]
    impact[95:] = [0, 0, 1]
    saturation = np.tile(np.array([8, -8, 8], dtype=np.float32), (200, 1))

    lines = ["// Generated by tools/generate_model_fixtures.py; do not edit by hand.",
             f"// Model SHA256: {hashlib.sha256(model).hexdigest()}",
             f"// ai-edge-litert {importlib.metadata.version('ai-edge-litert')}; "
             f"NumPy {np.__version__}; BUILTIN_REF kernels, one thread.",
             "#pragma once", "#include <cstdint>", "",
             "struct ModelFixture {", "    const char *name;",
             "    float raw[200][3];", "    int8_t quantized[600];",
             "    int8_t output;", "};", "",
             "inline constexpr ModelFixture kModelFixtures[] = {"]
    for name, raw in [("stationary", stationary), ("periodic", periodic),
                      ("impact", impact), ("saturation", saturation)]:
        standardized = (raw - mean) / scale
        quantized = np.clip(np.rint(standardized / np.float32(input_scale)) + input_zero,
                            -128, 127).astype(np.int8).reshape(1, 600)
        interpreter.set_tensor(input_info["index"], quantized)
        interpreter.invoke()
        output = int(interpreter.get_tensor(output_info["index"])[0, 0])
        lines.extend([f'    {{"{name}", {{'])
        for row in raw:
            lines.append("        {" + ", ".join(f"{float(x):.9e}f" for x in row) + "},")
        lines.append("    }, {")
        values = quantized.ravel().tolist()
        for i in range(0, len(values), 24):
            lines.append("        " + ", ".join(str(v) for v in values[i:i + 24]) + ",")
        lines.append(f"    }}, {output}}},")
        print(f"{name}: output={output}, score={(output - output_zero) * output_scale:.9g}")
    lines.extend(["};", ""])
    destination = ROOT / "tests/model_fixtures.h"
    destination.write_text("\n".join(lines))
    print(f"Wrote {destination}")


if __name__ == "__main__":
    main()
