#!/usr/bin/env python3
"""Freeze exported intermediate shapes for the fixed [1,600] TFLM deployment.

The supplied export has six stale intermediate batch dimensions. Desktop
LiteRT resolves them during Invoke; TFLM needs them stored before allocation.
Only shape-vector integers are patched. Weights, quantization and operators
remain byte-for-byte unchanged. The original main/new_model export is retained.
"""

import hashlib
from pathlib import Path
import re
import struct

import numpy as np
from ai_edge_litert import schema_py_generated as schema
from ai_edge_litert.interpreter import Interpreter, OpResolverType


ROOT = Path(__file__).resolve().parents[1]


def main():
    source = ROOT / "main/new_model/model_data.cc"
    original = bytes(int(v, 16) for v in re.findall(r"0x([0-9a-fA-F]{2})", source.read_text()))
    model = schema.Model.GetRootAsModel(original, 0)
    if model.SubgraphsLength() != 1:
        raise ValueError("This preparation tool requires one subgraph")
    graph = model.Subgraphs(0)
    interpreter = Interpreter(model_content=original, num_threads=1,
                              experimental_preserve_all_tensors=True,
                              experimental_op_resolver_type=OpResolverType.BUILTIN_REF)
    interpreter.allocate_tensors()
    input_info, = interpreter.get_input_details()
    output_info, = interpreter.get_output_details()
    if input_info["dtype"] != np.int8 or list(input_info["shape"]) != [1, 600]:
        raise ValueError("Expected INT8 input [1,600]")
    if output_info["dtype"] != np.int8 or list(output_info["shape"]) != [1, 1]:
        raise ValueError("Expected INT8 output [1,1]")
    interpreter.set_tensor(input_info["index"],
                           np.full((1, 600), input_info["quantization"][1], dtype=np.int8))
    interpreter.invoke()

    # Runtime-created scratch tensors are not serialized in the FlatBuffer.
    shapes = {t["index"]: list(map(int, t["shape"]))
              for t in interpreter.get_tensor_details() if t["index"] < graph.TensorsLength()}
    prepared = bytearray(original)
    changes = []
    for index, shape in shapes.items():
        tensor = graph.Tensors(index)
        stored = list(map(int, tensor.ShapeAsNumpy()))
        if stored == shape:
            continue
        if len(stored) != len(shape) or any(d <= 0 for d in shape):
            raise ValueError(f"Tensor {index}: cannot patch rank or dynamic dimensions")
        # Schema field 0 is Tensor.shape; use its existing vector so every
        # byte outside the corrected dimensions remains identical.
        vector = tensor._tab.Vector(tensor._tab.Offset(4))
        for axis, value in enumerate(shape):
            struct.pack_into("<i", prepared, vector + 4 * axis, value)
        changes.append(f"tensor {index}: {stored} -> {shape}")

    patched_graph = schema.Model.GetRootAsModel(prepared, 0).Subgraphs(0)
    for index, shape in shapes.items():
        # Also detects accidental edits through shared FlatBuffer vectors.
        if list(patched_graph.Tensors(index).ShapeAsNumpy()) != shape:
            raise ValueError(f"Unexpected shape change in tensor {index}")

    lines = ['#include "model_data.h"', "",
             "// Full integer INT8; intermediate shapes frozen for TFLite Micro.",
             f"// Original export SHA256: {hashlib.sha256(original).hexdigest()}",
             f"// Deployment TFLite SHA256: {hashlib.sha256(prepared).hexdigest()}",
             "// Generated by tools/prepare_int8_model.py from main/new_model."]
    lines.extend(f"// {change}" for change in changes)
    lines.append("alignas(16) const unsigned char g_fall_model[] = {")
    for i in range(0, len(prepared), 12):
        lines.append("    " + ", ".join(f"0x{value:02x}" for value in prepared[i:i + 12]) + ",")
    lines.extend(["};", "", "const unsigned int g_fall_model_len = sizeof(g_fall_model);", ""])
    (ROOT / "main/model/model_data.cc").write_text("\n".join(lines))
    print("\n".join(changes) or "All stored shapes already match")
    print(f"Prepared {len(prepared)} bytes; {sum(a != b for a, b in zip(original, prepared))} bytes changed")


if __name__ == "__main__":
    main()
